### PR TITLE
hspy read support and more error catches

### PR DESCRIPTION
**Pull request by jlaehne**
### Description of the change
- Adapted hspy-reader so that non-linear `DataAxis` is correctly read back into a signal object (by checking if a vector `axis` exists in the saved axes object).
- Added `non_linear_axis` to plugin characteristics, and added error message on write for file formats where this property is `False` (so far all but `hspy`)
- Additional catch in `roi.py`

### Progress of the PR
- [X] Change implemented (can be split into several points),
- [X] Add tests,
- [X] Debug,
- [X] Update docstrings,
- [X] ready for review.

### CODE REVIEW

**Comment by jlaehne** [comment]
@ercipre:
- While working on the `crop` function and tests, I came up with the need for some clarification on the use of `FunctionalDataAxis`. So far it is implemented with `x=np.arange(self.size)`, which is very limiting and e.g. does not support the implementation of cropping. Thus, I have used it by alternatively defining a vector `x0` as the input range for `expression` so that `axis = expression(x0)`, which I now also use for cropping. Theoretically, it would be possible to instead define `offset` and `scale` parameters for `x` that are updated when cropping. Would it be better to have both options, or does that make things too complicated?

**Comment by jlaehne** [comment]
@francisco-dlp: What do you think about the above question concerning `FunctionalDataAxis`. It needs some additional attribute. Either a vector `x0` or alternatively `scale` and `offset` to define the `x` vector used in the evaluation of the expression. Of course, these can also be included as additional variables in the expression (as basically done in the definition of LinearDataAxis), but then a general implementation of cropping, rebinning, or similar methods would not be feasible.

**Comment by francisco-dlp** [comment]
That's a possible solution that works. There is an alternative that doesn't involve storing `x0`: adding an ``offset`` parameter to the expression automatically i.e. replacing ``x`` by ``x - offset`` in the expression. I think that this is something that users will want anyway. This approach has the extra advantage that the ``crop`` method in linear axis should work as is if we move it to ``FunctionalDataAxis``.

Regarding the rest of this PR, I must admit that I've never been very happy with the way we store the axes information in HyperSpy. Now that we need to add support for extra types of axes, I think that it would be better to refactor the code rather than hacking it in order to make it work with the new axes. In particular, we could store them like we store model component's. For example

```python
{axes=[
              {
               'FunctionalDataAxis' : {'name' : "" etc},
               'LinearDataAxis': {'name'...]}
```

Of course, it we take this approach, it would be good to keep the format compatible with previous versions of HyperSpy when not using non-uniform axes. For that we could (maybe optionally) also store the linear axes using the current format. What do you think?

**Comment by jlaehne** [comment]
@ericpre: For the moment, I have removed any functionality related to `x0` for the `FunctionalDataAxis`. It makes more sense to have the changes to `FunctionalDataAxis` in a separate PR. Thus, reduced to mainly the IO-functionality, this PR should now be ready to be merged with your master branch, unless we opt to perform the changes to the storage format proposed by @francisco-dlp in this PR.

**Comment by jlaehne** [comment]
@francisco-dlp: Well, the only thing that was not supported by the current implementation was to read back an axis-vector instead of only attributes of the axes containing a single parameter each.

However, I see your point in adding the type of axis to the object that is saved for a cleaner implementation. If we opt to do so, I think it would be good if:
- the read function automatically works for the old and new formats
- the write function gets a legacy functionality that writes the axes without the additional information in the old format. This option does not need to be restricted to the case of a uniform axis, as the current writer saves all the attributes correctly, including the vector.

If we opt to change the storage format, should we do it in this PR or launch a new PR.

**Comment by francisco-dlp** [comment]
I think that it is indeed worth to improve the way we store the axes in this PR. Regarding how to do it, I agree with all your points except for the last one: saving non-uniform axes in legacy mode. Although it is true that HyperSpy <1.6 may be able to read such a file, the good news stop there since most operations won't work as expected on non-uniform axes. Therefore, I think that it is better not to support legacy saving of signals that contain non-uniform axes. In this way, somebody trying to load a signal containing non-uniform axes with hyperspy <1.6 will get an useful message explaining that upgrading HyperSpy is required to load the file.

**Pull request closed without merging**
