### PR TITLE
Derivative for non-linear axes

### PR DESCRIPTION
**Pull request by francisco-dlp**
This also:

* fixes BSS by using derivative instead of diff
* raises NotImplementedError when calling ``diff``, ``smooth_tv`` and ``smooth_savitzky_golay`` on signals with non-linear axes
* enables ``map`` for non-linear axes

### CODE REVIEW

**Comment by jlaehne** [comment]
`diff` should work for non-linear DataAxis, where an axis vector is given, implementation is only lacking for the FunctionalDataAxis.

**Comment by francisco-dlp** [comment]
If by working we mean that it is possible to compute it, I agree. But the question is, does it make any sense to compute such a thing? In my experience people tend to think that diff and derivative are equivalent. We have somehow encouraged this confusion in HyperSpy by recomputing the axis when using diff to make it coincide with the place where the numerical derivative computed using `diff` would be. This "confusion" is safe (except for a factor) when the axes are linear. However, when they are not, then the diff and the derivative are very different, so exchanging them to can lead to totally unexpected results. That's why I thought that it is a good idea to raise an error instead of returning something that most of the time is not what users want or expect. I have even considered deprecating ``diff`` also for linear axes, since I  am not sure that the concept makes sense in HyperSpy where, unlike in numpy, arrays have axes.

**Comment by jlaehne** [comment]
I agree. Just came back to this, because I had proposed a similar warning in #10 and @ericpre thought it was not necessary. In #10, I also considered adding a warning for `sum`, because I fear that users might use it as an approximation of an integral, which makes sense only for a linear axis - but as proposed by @ericpre, we should mention in the user guide (and potentially docstrings) that these methods make limited sense for a non-linear-axis and also for a linear axis they should not be used blindly. I will try to add that to #14.

**Comment by francisco-dlp** [comment]
Good point regarding ``sum``. Actually I think that the situation is even more subtle in this case, since ``sum`` would be equivalent to the integral, even in the case of non-uniform spacing, as long as the signal is binned, a roughly valid approximation (except again for a factor) for "non-binned" signals, and fully wrong, as you point out, for non-uniformly spaced axes of non-binned signals.

I agree that, in the context of HyperSpy, most people mean ``integrate`` when they write ``sum`` and that this may lead to wrong results (as in the case of ``diff``) when dealing with non-uniform axes. So, this is another candidate for deprecation.

As we are planning to release 2.0, where we are going to break plenty of things, it is in principle possible to deprecate those and other problematic functions. However, in practice, this may break a lot of scripts. So I think that your original idea of warning the user when using certain functions with non-uniform axes may be the best compromise.

**Comment by jlaehne** [comment]
I don't have an example at hand, but I guess there may even be examples where people might actually want to just have the sums or differences - so no need to deprecate all that, but I will see that I would then add warnings to the functions, and mention it in dosctrings as well as documentation (with the advice that a proper integration or derivative might be the appropriate solutions).

**Pull request merged**
